meta-ti-bsp: add back u-boot-ti-staging
Issue: LIN1024-10701

Add back u-boot-ti-staging_2023.04.bb as this is removed by the upstream
commit[1]. This is to fix the following build errors:

WARNING: No recipes in default available for:
  /buildarea5/workspace/24buildti/layers/ti-am335x/recipes-bsp/u-boot/u-boot-ti-staging_2023.04.bbappend
  /buildarea5/workspace/24buildti/layers/ti-am335x/recipes-graphics/mesa/mesa-pvr_22.3.5.bbappend
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'u-boot-ti-staging'
u-boot-ti-staging was skipped: incompatible with machine ti-am335x (not in COMPATIBLE_MACHINE)
u-boot-ti-staging was skipped: incompatible with machine ti-am335x (not in COMPATIBLE_MACHINE)

[1] http://lxgit.wrs.com/cgit/layers/meta-ti.git/commit/meta-ti-bsp/recipes-graphics/mesa?h=WRLINUX_10_24_LTS&id=b5649a38b8d7a79bbdd6011724fe9b560288bd4f

(LOCAL REV: NOT UPSTREAM) - Wrlinux specific

Signed-off-by: Jinfeng Wang <jinfeng.wang.cn@windriver.com>